modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
logoFile="icon.png"

[[mods]]
modId="golden_apple_tree"
version="${forge_mod_version}"
displayName="${mod_name}"
authors="${mod_author}"
description='''${mod_description}'''
updateJSONURL="https://raw.githubusercontent.com/skniro/maven3/main/com/skniro/GoldenAppleTree/update/forge.json" #optional
displayURL="https://www.skniro.org"
issueTrackerURL="https://github.com/skniro/GoldenAppleTree/issues"

[[dependencies.golden_apple_tree]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.golden_apple_tree]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"