# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html

minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.16.9
mapping_channel=official
mapping_version=1.20.1

# Mod Properties
fabric_mod_version=1.2.0-1.20.1-Fabric
forge_mod_version=1.2.0-1.20.1-Forge
neoforge_mod_version=1.2.0-1.20.1-NeoForge
maven_group=com.skniro
archives_base_name=Golden_Apple_Tree
mod_id=golden_apple_tree
mod_author=skniro

#Fabric api
fabric_version=0.92.2+1.20.1
forge_version=47.3.0
jade_version=11.13.1
jade_forge_version=11.13.2

# Neoforge Properties
minecraft_version_range=[1.20,1.21)
mod_name=Golden_Apple_Tree
mod_license=MIT License
mod_group_id=com.skniro.golden_apple_tree
mod_description=

# Neoforge
neo_version=21.1.93
neo_version_range=[21.0,)
loader_version_range=[2,)
forge_version_range=[21,)